import localFont from 'next/font/local';
import '@/styles/reset.scss';
import { ScrollProvider } from '@/lib/providers/ScrollProvider/ScrollProvider';
import { LocaleProvider } from '@/lib/providers/LocaleContext/LocaleContext';
import { ModalProvider } from '@/lib/providers/ModalProvider/ModalProvider';
import Script from 'next/script';
const neueHaasDisplay = localFont({
  src: [
    {
      path: './fonts/NeueHaasDisplay/NeueHaasDisplayBold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/NeueHaasDisplay/NeueHaasDisplayRoman.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-neue-haas-display',
});

const hovesPro = localFont({
  src: [
    {
      path: './fonts/TTHovesPro/TTHovesProVariable.ttf',
      style: 'normal',
    },
  ],
  variable: '--font-hoves-pro',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="html">
      <head>
        <Script
          dangerouslySetInnerHTML={{
            __html: `(function(c,s,q,u,a,r,e){c.hj=c.hj||function(){(c.hj.q=c.hj.q||[]).push(arguments)};c._hjSettings={hjid:a};r=s.getElementsByTagName('head')[0];e=s.createElement('script');e.async=true;e.src=q+c._hjSettings.hjid+u;r.appendChild(e);})(window,document,'https://static.hj.contentsquare.net/c/csq-', '.js', 6395816);`, // Замените 6395816 на ваш ID Hotjar
          }}
        />
        <Script
          dangerouslySetInnerHTML={{
            __html: `
      const setCookie = (name, value, days) => {
        const d = new Date();
        d.setTime(d.getTime() + 24 * 60 * 60 * 1000 * days);
        document.cookie = \`\${name}=\${value};path=/;expires=\${d.toGMTString()}\`;
      };

      const getCookie = (name) => {
        const v = document.cookie.match('(^|;) ?' + name + '=([^;]*)(;|$)');
        return v ? v[2] : null;
      };

      const getSubId = () => {
        const params = new URLSearchParams(window.location.search.substr(1));
        return (
          params.get('_subid') ||
          params.get('subid') ||
          getCookie('subid') ||
          '{subid}'
        );
      };

      const getToken = () => {
        const params = new URLSearchParams(window.location.search.substr(1));
        return (
          params.get('_token') ||
          params.get('token') ||
          getCookie('token') ||
          '{token}'
        );
      };

      const getAff = () => {
        const params = new URLSearchParams(window.location.search.substr(1));
        return params.get('aff') || getCookie('aff') || '{aff}';
      };

      const getFlow = () => {
        const params = new URLSearchParams(window.location.search.substr(1));
        return params.get('flow') || getCookie('flow') || '{flow}';
      };

      const getPixel = () => {
        const params = new URLSearchParams(window.location.search.substr(1));
        return params.get('pixel') || getCookie('pixel') || '{pixel}';
      };

      // Этот код выполнится только в браузере (клиентская логика)
      const subid = getSubId();
      const token = getToken();
      const aff = getAff();
      const flow = getFlow();
      const pixel = getPixel();

      setCookie('pixel', pixel, 5);
      setCookie('token', token, 5);
      setCookie('subid', subid, 5);
      setCookie('aff', aff, 5);
      setCookie('flow', flow, 5);

      // Инициализация пикселя Facebook
      var date = new Date();
      date.setTime(date.getTime() + 5 * 24 * 60 * 60 * 1000);
      document.cookie = 'pixel=' + pixel + ';expires=' + date.toUTCString();

      var matches = document.cookie.match(new RegExp('(?:^|; )' + 'pixel' + '=([^;]*)'));
      var pixelCookie = matches ? decodeURIComponent(matches[1]) : undefined;

      !(function(f, b, e, v, n, t, s) {
        if (f.fbq) return;
        n = f.fbq = function() {
          n.callMethod ? n.callMethod.apply(n, arguments) : n.queue.push(arguments);
        };
        if (!f._fbq) f._fbq = n;
        n.push = n;
        n.loaded = !0;
        n.version = '2.0';
        n.queue = [];
        t = b.createElement(e);
        t.async = !0;
        t.src = v;
        s = b.getElementsByTagName(e)[0];
        s.parentNode.insertBefore(t, s);
      })(window, document, 'script', 'https://connect.facebook.net/en_US/fbevents.js');

      fbq('init', pixelCookie);
      fbq('track', 'PageView');
    `,
          }}
        />
      </head>
      <body className={`${hovesPro.variable} body`}>
        <ScrollProvider scrollBar></ScrollProvider>
        <LocaleProvider>
          <ModalProvider>{children}</ModalProvider>
        </LocaleProvider>
      </body>
    </html>
  );
}
